// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/shoppinghistoryservice.proto

package shoppinghistory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShoppingHistoryServiceClient is the client API for ShoppingHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShoppingHistoryServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error)
	GetOrdersOfUser(ctx context.Context, in *GetOrdersOfUserRequest, opts ...grpc.CallOption) (*Orders, error)
	DeleteOrder(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*Empty, error)
}

type shoppingHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShoppingHistoryServiceClient(cc grpc.ClientConnInterface) ShoppingHistoryServiceClient {
	return &shoppingHistoryServiceClient{cc}
}

func (c *shoppingHistoryServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/shoppinghistoryservice.ShoppingHistoryService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingHistoryServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/shoppinghistoryservice.ShoppingHistoryService/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingHistoryServiceClient) GetOrdersOfUser(ctx context.Context, in *GetOrdersOfUserRequest, opts ...grpc.CallOption) (*Orders, error) {
	out := new(Orders)
	err := c.cc.Invoke(ctx, "/shoppinghistoryservice.ShoppingHistoryService/GetOrdersOfUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingHistoryServiceClient) DeleteOrder(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/shoppinghistoryservice.ShoppingHistoryService/DeleteOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShoppingHistoryServiceServer is the server API for ShoppingHistoryService service.
// All implementations should embed UnimplementedShoppingHistoryServiceServer
// for forward compatibility
type ShoppingHistoryServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*Order, error)
	GetOrder(context.Context, *GetOrderRequest) (*Order, error)
	GetOrdersOfUser(context.Context, *GetOrdersOfUserRequest) (*Orders, error)
	DeleteOrder(context.Context, *DeleteOrderRequest) (*Empty, error)
}

// UnimplementedShoppingHistoryServiceServer should be embedded to have forward compatible implementations.
type UnimplementedShoppingHistoryServiceServer struct {
}

func (UnimplementedShoppingHistoryServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedShoppingHistoryServiceServer) GetOrder(context.Context, *GetOrderRequest) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedShoppingHistoryServiceServer) GetOrdersOfUser(context.Context, *GetOrdersOfUserRequest) (*Orders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersOfUser not implemented")
}
func (UnimplementedShoppingHistoryServiceServer) DeleteOrder(context.Context, *DeleteOrderRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrder not implemented")
}

// UnsafeShoppingHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShoppingHistoryServiceServer will
// result in compilation errors.
type UnsafeShoppingHistoryServiceServer interface {
	mustEmbedUnimplementedShoppingHistoryServiceServer()
}

func RegisterShoppingHistoryServiceServer(s grpc.ServiceRegistrar, srv ShoppingHistoryServiceServer) {
	s.RegisterService(&ShoppingHistoryService_ServiceDesc, srv)
}

func _ShoppingHistoryService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingHistoryServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppinghistoryservice.ShoppingHistoryService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingHistoryServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingHistoryService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingHistoryServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppinghistoryservice.ShoppingHistoryService/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingHistoryServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingHistoryService_GetOrdersOfUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersOfUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingHistoryServiceServer).GetOrdersOfUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppinghistoryservice.ShoppingHistoryService/GetOrdersOfUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingHistoryServiceServer).GetOrdersOfUser(ctx, req.(*GetOrdersOfUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingHistoryService_DeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingHistoryServiceServer).DeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shoppinghistoryservice.ShoppingHistoryService/DeleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingHistoryServiceServer).DeleteOrder(ctx, req.(*DeleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShoppingHistoryService_ServiceDesc is the grpc.ServiceDesc for ShoppingHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShoppingHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shoppinghistoryservice.ShoppingHistoryService",
	HandlerType: (*ShoppingHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _ShoppingHistoryService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _ShoppingHistoryService_GetOrder_Handler,
		},
		{
			MethodName: "GetOrdersOfUser",
			Handler:    _ShoppingHistoryService_GetOrdersOfUser_Handler,
		},
		{
			MethodName: "DeleteOrder",
			Handler:    _ShoppingHistoryService_DeleteOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shoppinghistoryservice.proto",
}
